---
AWSTemplateFormatVersion: "2010-09-09"
Description: This template will launch various core services such as CodeCommit & ECR for Modernization Workshop.

Resources:
  CodeRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: ld-aws-workshop
      RepositoryDescription: LaunchDarkly Workshop CodeCommit Repo

Outputs:
  CodeRepoURL:
    Description: URL for code commit repo
    Value: !GetAtt CodeRepo.CloneUrlHttp
    Export:
      Name: WorkshopServices:CodeRepoURL
